import type { Crop } from '@/types';

const crops: Crop[] = [
  // Cereales y granos
  { 
    id: '1', 
    nombre: 'Arroz',
    nombreCientifico: 'Oryza sativa',
    familia: 'Poaceae',
    region: 'Orinoquía', 
    clima: 'Cálido', 
    descripcionDetallada: 'Cereal semiacuático fundamental en la dieta colombiana, cultivado tradicionalmente en campos inundados que requieren altas temperaturas y agua constante.',
    temporada: 'Abril - Junio',
    tipoDeSuelo: 'Arcilloso, impermeable para retener el agua.',
    tiempoSiembra: 'Directa o por trasplante desde semilleros.',
    tiempoCosecha: '4-6 meses.',
    plagasComunes: 'Sogata, Piricularia.',
    imageUrl: 'https://placehold.co/600x400.png', 
    dataAiHint: 'rice paddy'
  },
  { 
    id: '2', 
    nombre: 'Maíz',
    nombreCientifico: 'Zea mays',
    familia: 'Poaceae',
    region: 'Andina', 
    clima: 'Templado', 
    descripcionDetallada: 'Uno de los cereales más cultivados del mundo. Requiere riego moderado, pleno sol y es bastante adaptable a diferentes condiciones.',
    temporada: 'Marzo - Mayo',
    tipoDeSuelo: 'Franco, rico en materia orgánica y con buen drenaje.',
    tiempoSiembra: '1-2 semanas para germinar.',
    tiempoCosecha: '3-4 meses desde la siembra.',
    plagasComunes: 'Gusano cogollero, araña roja.',
    imageUrl: 'https://placehold.co/600x400.png', 
    dataAiHint: 'corn field'
  },
  {
    id: '3',
    nombre: 'Trigo',
    nombreCientifico: 'Triticum aestivum',
    familia: 'Poaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Cereal de clima frío, importante para la producción de harina. Se cultiva en las zonas altas de Boyacá y Cundinamarca.',
    temporada: 'Mayo - Junio',
    tipoDeSuelo: 'Franco-arcilloso, profundo y bien drenado.',
    tiempoSiembra: 'Siembra directa, germina en 1-2 semanas.',
    tiempoCosecha: '5-6 meses.',
    plagasComunes: 'Roya del tallo, pulgones.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'wheat field'
  },
  {
    id: '4',
    nombre: 'Sorgo',
    nombreCientifico: 'Sorghum bicolor',
    familia: 'Poaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Grano resistente a la sequía y altas temperaturas, utilizado para alimentación animal y humana.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Adaptable, prefiere suelos francos a arcillosos.',
    tiempoSiembra: 'Siembra directa, 3-7 días para germinar.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mosca del sorgo, pulgón amarillo.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sorghum field'
  },
  {
    id: '5',
    nombre: 'Cebada',
    nombreCientifico: 'Hordeum vulgare',
    familia: 'Poaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Cereal utilizado principalmente para la producción de malta para cerveza y alimentación de ganado. Crece en altiplanos.',
    temporada: 'Abril - Junio',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Roya, oídio.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'barley field'
  },
  {
    id: '6',
    nombre: 'Avena',
    nombreCientifico: 'Avena sativa',
    familia: 'Poaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Cereal de clima frío cultivado por su grano nutritivo. Se usa en hojuelas, harina y como forraje.',
    temporada: 'Mayo - Julio',
    tipoDeSuelo: 'Franco, tolera suelos ácidos.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Roya de la corona, carbón.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'oat field'
  },

  // Tubérculos y raíces
  { 
    id: '7', 
    nombre: 'Papa Criolla',
    nombreCientifico: 'Solanum phureja',
    familia: 'Solanaceae',
    region: 'Andina', 
    clima: 'Frío', 
    descripcionDetallada: 'Variedad de papa nativa de los Andes, de piel delgada y carne amarilla. Rápido crecimiento y cocción.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco arenoso, suelto y bien drenado.',
    tiempoSiembra: '3-4 semanas para brotar.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Gota, polilla guatemalteca.',
    imageUrl: 'https://placehold.co/600x400.png', 
    dataAiHint: 'yellow potatoes'
  },
  {
    id: '8',
    nombre: 'Papa Pastusa',
    nombreCientifico: 'Solanum tuberosum (Grupo Andigenum)',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Variedad de papa común en el sur de Colombia, ideal para sopas y purés por su textura harinosa.',
    temporada: 'Principalmente segundo semestre.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Siembra de tubérculos.',
    tiempoCosecha: '5-6 meses.',
    plagasComunes: 'Gota (Phytophthora infestans), gusano blanco.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'potato harvest'
  },
  {
    id: '9',
    nombre: 'Yuca',
    nombreCientifico: 'Manihot esculenta',
    familia: 'Euphorbiaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Raíz tuberosa fundamental en la dieta de zonas tropicales. Es tolerante a la sequía y a suelos pobres.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco-arenoso, bien drenado.',
    tiempoSiembra: 'Propagación por estacas.',
    tiempoCosecha: '8-12 meses.',
    plagasComunes: 'Ácaros, mosca blanca.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'cassava plant'
  },
  {
    id: '10',
    nombre: 'Ñame',
    nombreCientifico: 'Dioscorea spp.',
    familia: 'Dioscoreaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Tubérculo de gran importancia en la costa Caribe. Requiere tutores para su crecimiento trepador.',
    temporada: 'Abril - Mayo',
    tipoDeSuelo: 'Franco, profundo y rico en materia orgánica.',
    tiempoSiembra: 'Siembra de trozos del tubérculo.',
    tiempoCosecha: '8-10 meses.',
    plagasComunes: 'Antracnosis, cochinillas.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'yam plant'
  },
  {
    id: '11',
    nombre: 'Arracacha',
    nombreCientifico: 'Arracacia xanthorrhiza',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Raíz andina de sabor dulce y anisado, utilizada en sopas y purés. Se cultiva entre 1,800 y 2,500 msnm.',
    temporada: 'Marzo - Mayo',
    tipoDeSuelo: 'Franco, suelto y bien drenado.',
    tiempoSiembra: 'Propagación por cormos.',
    tiempoCosecha: '10-14 meses.',
    plagasComunes: 'Gusanos trozadores, nematodos.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'arracacha root'
  },

  // Leguminosas y oleaginosas
  {
    id: '12',
    nombre: 'Frijol Cargamanto',
    nombreCientifico: 'Phaseolus vulgaris',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Variedad de frijol grande y de color rojo moteado, fundamental en platos típicos como la bandeja paisa.',
    temporada: 'Variable, dos ciclos al año.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses (seco).',
    plagasComunes: 'Antracnosis, mosca blanca.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'red beans'
  },
  {
    id: '13',
    nombre: 'Soya',
    nombreCientifico: 'Glycine max',
    familia: 'Fabaceae',
    region: 'Orinoquía',
    clima: 'Cálido',
    descripcionDetallada: 'Oleaginosa de gran importancia industrial para la producción de aceite y torta de soya para alimento animal.',
    temporada: 'Primer y segundo semestre.',
    tipoDeSuelo: 'Franco-arcilloso, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Chinches, gusano cogollero.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'soybean field'
  },
  {
    id: '14',
    nombre: 'Lenteja',
    nombreCientifico: 'Lens culinaris',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Leguminosa de grano pequeño y alto valor nutritivo. Colombia importa la mayor parte de su consumo.',
    temporada: 'Mayo - Junio',
    tipoDeSuelo: 'Franco, bien drenado, tolera suelos pobres.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Pulgones, gorgojos.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'lentil plant'
  },

  // Cultivos industriales y de exportación
  { 
    id: '15', 
    nombre: 'Café', 
    nombreCientifico: 'Coffea arabica',
    familia: 'Rubiaceae',
    region: 'Andina', 
    clima: 'Templado', 
    descripcionDetallada: 'El café colombiano es mundialmente famoso. Crece mejor en laderas de montañas con sombra parcial. Requiere alta humedad y suelos de origen volcánico.',
    temporada: 'Septiembre - Diciembre',
    tipoDeSuelo: 'Volcánico, profundo y con buen drenaje.',
    tiempoSiembra: '6-12 meses en vivero antes de trasplantar.',
    tiempoCosecha: '3-4 años para la primera cosecha.',
    plagasComunes: 'Broca del café, roya.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'coffee plant'
  },
  {
    id: '16',
    nombre: 'Caña de Azúcar',
    nombreCientifico: 'Saccharum officinarum',
    familia: 'Poaceae',
    region: 'Andina', // Valle del Cauca
    clima: 'Cálido',
    descripcionDetallada: 'Cultivo industrial clave para la producción de azúcar y etanol. Requiere altas temperaturas y abundante agua.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco a arcilloso, profundo.',
    tiempoSiembra: 'Propagación por esquejes (tallos).',
    tiempoCosecha: '12-16 meses.',
    plagasComunes: 'Diatraea (barrenador del tallo), carbón.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sugar cane'
  },
  {
    id: '17',
    nombre: 'Palma Africana',
    nombreCientifico: 'Elaeis guineensis',
    familia: 'Arecaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Palma cultivada extensivamente para la producción de aceite de palma, usado en alimentos y biocombustibles.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Suelos profundos, bien drenados.',
    tiempoSiembra: 'Vivero por 12-15 meses.',
    tiempoCosecha: '3-4 años para iniciar producción.',
    plagasComunes: 'Pudrición del cogollo, picudo de la palma.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'oil palm'
  },
  {
    id: '18',
    nombre: 'Cacao',
    nombreCientifico: 'Theobroma cacao',
    familia: 'Malvaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Árbol de cuyo fruto se extrae el chocolate. Crece bajo sombra en selvas húmedas tropicales.',
    temporada: 'Abril - Junio',
    tipoDeSuelo: 'Franco arcilloso, rico en materia orgánica.',
    tiempoSiembra: '4-6 meses en vivero.',
    tiempoCosecha: '3-5 años para la primera cosecha.',
    plagasComunes: 'Monilia, escoba de bruja.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'cacao pod'
  },

  // Frutas tropicales y andinas
  { 
    id: '19', 
    nombre: 'Banano',
    nombreCientifico: 'Musa sapientum',
    familia: 'Musaceae',
    region: 'Caribe', 
    clima: 'Cálido', 
    descripcionDetallada: 'Una de las frutas de exportación más importantes de Colombia. Requiere mucho sol, agua y suelos ricos.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco, profundo y rico en materia orgánica.',
    tiempoSiembra: 'Se propaga por cormos o hijuelos.',
    tiempoCosecha: '9-12 meses después de la siembra.',
    plagasComunes: 'Picudo negro, Sigatoka negra.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'banana tree'
  },
  { 
    id: '20', 
    nombre: 'Plátano',
    nombreCientifico: 'Musa paradisiaca',
    familia: 'Musaceae',
    region: 'Andina', 
    clima: 'Templado', 
    descripcionDetallada: 'Base de la alimentación en Colombia. Necesita sol, agua constante y suelos muy ricos en materia orgánica.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco, profundo y rico en materia orgánica.',
    tiempoSiembra: 'Se propaga por cormos o hijuelos.',
    tiempoCosecha: '9-12 meses después de la siembra.',
    plagasComunes: 'Picudo negro, Moko.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'plantain tree'
  },
  {
    id: '21',
    nombre: 'Piña',
    nombreCientifico: 'Ananas comosus',
    familia: 'Bromeliaceae',
    region: 'Andina', // Santander
    clima: 'Cálido',
    descripcionDetallada: 'Fruta tropical de gran demanda. La planta es una bromelia terrestre que requiere suelos bien drenados y ácidos.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco-arenoso, ácido y con buen drenaje.',
    tiempoSiembra: 'Propagación por coronas o hijuelos.',
    tiempoCosecha: '18-24 meses.',
    plagasComunes: 'Cochinilla harinosa, barrenador del fruto.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'pineapple plant'
  },
  { 
    id: '22', 
    nombre: 'Mango',
    nombreCientifico: 'Mangifera indica',
    familia: 'Anacardiaceae',
    region: 'Caribe', 
    clima: 'Cálido', 
    descripcionDetallada: 'Árbol tropical que necesita pleno sol y mucho espacio. Una poda anual ayuda a mejorar la producción.',
    temporada: 'Mayo - Agosto',
    tipoDeSuelo: 'Profundo y bien drenado. Tolera varios tipos de suelo.',
    tiempoSiembra: 'Se propaga por injerto.',
    tiempoCosecha: '3-5 años para la primera cosecha.',
    plagasComunes: 'Mosca de la fruta, antracnosis.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'mango tree'
  },
  {
    id: '23',
    nombre: 'Maracuyá',
    nombreCientifico: 'Passiflora edulis',
    familia: 'Passifloraceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Planta trepadora cuyo fruto ácido es muy apreciado para jugos y postres. Requiere espalderas o soporte.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco, bien drenado, rico en materia orgánica.',
    tiempoSiembra: 'Por semilla o esquejes.',
    tiempoCosecha: '6-9 meses.',
    plagasComunes: 'Mosca del ovario, secadera.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'passion fruit'
  },
  {
    id: '24',
    nombre: 'Aguacate',
    nombreCientifico: 'Persea americana',
    familia: 'Lauraceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Árbol de gran importancia económica (variedad Hass). No tolera el encharcamiento y es sensible a vientos fuertes.',
    temporada: 'Variable según la variedad.',
    tipoDeSuelo: 'Franco arenoso, profundo y con excelente drenaje.',
    tiempoSiembra: 'Por injerto para asegurar calidad.',
    tiempoCosecha: '3-5 años (injertado).',
    plagasComunes: 'Tristeza del aguacatero, barrenadores.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'avocado tree'
  },

  // Hortalizas
  {
    id: '25',
    nombre: 'Tomate de Mesa',
    nombreCientifico: 'Solanum lycopersicum',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de fruto más cultivada a nivel mundial. Requiere tutorado para mantener la planta erguida y ventilada.',
    temporada: 'Todo el año (en invernadero).',
    tipoDeSuelo: 'Franco, rico en materia orgánica, buen drenaje.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mosca blanca, tuta absoluta, gota.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'tomato plant'
  },
  {
    id: '26',
    nombre: 'Cebolla Cabezona',
    nombreCientifico: 'Allium cepa',
    familia: 'Amaryllidaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Hortaliza de bulbo indispensable en la cocina. El curado al sol tras la cosecha es clave para su conservación.',
    temporada: 'Variable.',
    tipoDeSuelo: 'Franco, suelto y bien drenado.',
    tiempoSiembra: 'Trasplante o siembra directa.',
    tiempoCosecha: '4-6 meses.',
    plagasComunes: 'Mildeo velloso, trips.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'onion patch'
  },
  {
    id: '27',
    nombre: 'Zanahoria',
    nombreCientifico: 'Daucus carota',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de raíz muy popular. Requiere suelos sueltos y profundos para el correcto desarrollo de la raíz.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco-arenoso, profundo y sin piedras.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mosca de la zanahoria, nematodos.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'carrot patch'
  },
  {
    id: '28',
    nombre: 'Lechuga',
    nombreCientifico: 'Lactuca sativa',
    familia: 'Asteraceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de hoja de ciclo corto. Sensible al calor, que puede inducir una floración prematura (subida a flor).',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Siembra directa o trasplante.',
    tiempoCosecha: '2-3 meses.',
    plagasComunes: 'Pulgones, babosas, mildeo velloso.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'lettuce patch'
  },

  // Flores / Ornamentales
  {
    id: '29',
    nombre: 'Rosa',
    nombreCientifico: 'Rosa spp.',
    familia: 'Rosaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Una de las flores de exportación más importantes de Colombia. Se cultiva bajo invernadero en la Sabana de Bogotá.',
    temporada: 'Producción continua.',
    tipoDeSuelo: 'Franco-arcilloso, rico y bien drenado.',
    tiempoSiembra: 'Propagación por esquejes o injertos.',
    tiempoCosecha: 'La producción inicia a los 4-6 meses.',
    plagasComunes: 'Ácaros, mildeo polvoso, botrytis.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'rose garden'
  },
  {
    id: '30',
    nombre: 'Clavel',
    nombreCientifico: 'Dianthus caryophyllus',
    familia: 'Caryophyllaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Flor de corte de gran tradición y volumen de exportación. Requiere desbotones para obtener una flor principal de calidad.',
    temporada: 'Producción continua.',
    tipoDeSuelo: 'Franco-arenoso, con buen drenaje y pH neutro.',
    tiempoSiembra: 'Propagación por esquejes.',
    tiempoCosecha: 'La producción inicia a los 5-6 meses.',
    plagasComunes: 'Trips, roya, fusarium.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'carnation flowers'
  },
  {
    id: '31',
    nombre: 'Orquídea',
    nombreCientifico: 'Cattleya trianae (y otras)',
    familia: 'Orchidaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Flor nacional de Colombia. Muchas son epífitas, por lo que crecen sobre los árboles y no en tierra.',
    temporada: 'Variable según la especie.',
    tipoDeSuelo: 'Sustrato a base de corteza, no suelo común.',
    tiempoSiembra: 'Propagación por división de pseudobulbos.',
    tiempoCosecha: ' ornamental, no aplica cosecha.',
    plagasComunes: 'Cochinillas, pulgones.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'orchid flower'
  },

  // Aromáticas / Medicinales / Especias
  {
    id: '32',
    nombre: 'Cilantro',
    nombreCientifico: 'Coriandrum sativum',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hierba aromática indispensable en la cocina colombiana. De rápido crecimiento y sensible al calor excesivo.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, suelto y con buen drenaje.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '40-60 días.',
    plagasComunes: 'Pulgones, hongos foliares.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'coriander plant'
  },
  {
    id: '33',
    nombre: 'Manzanilla',
    nombreCientifico: 'Matricaria recutita',
    familia: 'Asteraceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Hierba medicinal muy popular por sus propiedades calmantes. Se utilizan sus flores para infusiones.',
    temporada: 'Siembra en primavera.',
    tipoDeSuelo: 'Bien drenado, no muy exigente.',
    tiempoSiembra: 'Siembra directa o trasplante.',
    tiempoCosecha: 'Las flores se cosechan a los 2-3 meses.',
    plagasComunes: 'Pulgones.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'chamomile flowers'
  },
  {
    id: '34',
    nombre: 'Jengibre',
    nombreCientifico: 'Zingiber officinale',
    familia: 'Zingiberaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Planta cuyo rizoma (tallo subterráneo) es muy apreciado como especia y medicinal. Prefiere sombra parcial.',
    temporada: 'Inicio de la temporada de lluvias.',
    tipoDeSuelo: 'Franco, rico en materia orgánica, bien drenado.',
    tiempoSiembra: 'Plantación de trozos del rizoma.',
    tiempoCosecha: '8-10 meses.',
    plagasComunes: 'Bacteriosis, nematodos.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ginger plant'
  },

  // Otros peculiares o emergentes
  {
    id: '35',
    nombre: 'Quinua',
    nombreCientifico: 'Chenopodium quinoa',
    familia: 'Amaranthaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Pseudocereal andino de alto valor nutricional. Adaptado a condiciones de altura y suelos marginales.',
    temporada: 'Abril - Mayo',
    tipoDeSuelo: 'Franco-arenoso, tolera salinidad.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '5-7 meses.',
    plagasComunes: 'Mildeo, polillas.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'quinoa field'
  },
  { 
    id: '36', 
    nombre: 'Chontaduro',
    nombreCientifico: 'Bactris gasipaes',
    familia: 'Arecaceae',
    region: 'Pacífica', 
    clima: 'Húmedo', 
    descripcionDetallada: 'Palmera nativa cuyo fruto es muy nutritivo y popular en la región Pacífica. Requiere alta humedad y calor.',
    temporada: 'Enero - Abril',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Por semilla, la germinación es lenta.',
    tiempoCosecha: '3-5 años para empezar a producir.',
    plagasComunes: 'Picudo de la palma, Gualpa.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'peach palm'
  },
  {
    id: '37',
    nombre: 'Lulo',
    nombreCientifico: 'Solanum quitoense',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Fruta andina de sabor exótico, muy usada en jugos. Planta arbustiva sensible a nematodos y plagas.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica, buen drenaje.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '6-8 meses.',
    plagasComunes: 'Nematodos, perforador del fruto.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'lulo fruit'
  },
];

// In a real app, this function would fetch data from a Firestore collection.
export async function getCrops(): Promise<Crop[]> {
  // Simulate network delay to mimic a real API call
  await new Promise(resolve => setTimeout(resolve, 200));
  return crops;
}

// In a real app, this would fetch a specific crop by its ID from Firestore.
export async function getCropById(id: string): Promise<Crop | undefined> {
  await new Promise(resolve => setTimeout(resolve, 100));
  return crops.find(crop => crop.id === id);
}
