import type { Crop } from '@/types';

const crops: Crop[] = [
  // 🌾 Cereales y granos
  { 
    id: '1', 
    nombre: 'Arroz',
    tipo: 'Cereales y granos',
    nombreCientifico: 'Oryza sativa',
    familia: 'Poaceae',
    region: 'Orinoquía', 
    clima: 'Cálido', 
    descripcionDetallada: 'Cereal semiacuático fundamental en la dieta colombiana, cultivado tradicionalmente en campos inundados que requieren altas temperaturas y agua constante.',
    temporada: 'Abril - Junio',
    tipoDeSuelo: 'Arcilloso, impermeable para retener el agua.',
    tiempoSiembra: 'Directa o por trasplante desde semilleros.',
    tiempoCosecha: '4-6 meses.',
    plagasComunes: 'Sogata, Piricularia.',
    imageUrl: 'https://images.pexels.com/photos/156323/rice-paddy-fields-asia-farm-156323.jpeg', 
    dataAiHint: 'rice paddy'
  },
  { 
    id: '2', 
    nombre: 'Maíz',
    tipo: 'Cereales y granos',
    nombreCientifico: 'Zea mays',
    familia: 'Poaceae',
    region: 'Andina', 
    clima: 'Templado', 
    descripcionDetallada: 'Uno de los cereales más cultivados del mundo. Requiere riego moderado, pleno sol y es bastante adaptable a diferentes condiciones.',
    temporada: 'Marzo - Mayo',
    tipoDeSuelo: 'Franco, rico en materia orgánica y con buen drenaje.',
    tiempoSiembra: '1-2 semanas para germinar.',
    tiempoCosecha: '3-4 meses desde la siembra.',
    plagasComunes: 'Gusano cogollero, araña roja.',
    imageUrl: 'https://images.pexels.com/photos/547264/pexels-photo-547264.jpeg', 
    dataAiHint: 'corn field'
  },
  {
    id: '3',
    nombre: 'Trigo',
    tipo: 'Cereales y granos',
    nombreCientifico: 'Triticum aestivum',
    familia: 'Poaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Cereal de clima frío, importante para la producción de harina. Se cultiva en las zonas altas de Boyacá y Cundinamarca.',
    temporada: 'Mayo - Junio',
    tipoDeSuelo: 'Franco-arcilloso, profundo y bien drenado.',
    tiempoSiembra: 'Siembra directa, germina en 1-2 semanas.',
    tiempoCosecha: '5-6 meses.',
    plagasComunes: 'Roya del tallo, pulgones.',
    imageUrl: 'https://images.pexels.com/photos/433333/pexels-photo-433333.jpeg',
    dataAiHint: 'wheat field'
  },
  {
    id: '4',
    nombre: 'Sorgo',
    tipo: 'Cereales y granos',
    nombreCientifico: 'Sorghum bicolor',
    familia: 'Poaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Grano resistente a la sequía y altas temperaturas, utilizado para alimentación animal y humana.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Adaptable, prefiere suelos francos a arcillosos.',
    tiempoSiembra: 'Siembra directa, 3-7 días para germinar.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mosca del sorgo, pulgón amarillo.',
    imageUrl: 'https://images.pexels.com/photos/259091/pexels-photo-259091.jpeg',
    dataAiHint: 'sorghum field'
  },
  {
    id: '5',
    nombre: 'Cebada',
    tipo: 'Cereales y granos',
    nombreCientifico: 'Hordeum vulgare',
    familia: 'Poaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Cereal utilizado principalmente para la producción de malta para cerveza y alimentación de ganado. Crece en altiplanos.',
    temporada: 'Abril - Junio',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Roya, oídio.',
    imageUrl: 'https://images.pexels.com/photos/163346/barley-field-cereals-agriculture-farmland-163346.jpeg',
    dataAiHint: 'barley field'
  },
  {
    id: '6',
    nombre: 'Avena',
    tipo: 'Cereales y granos',
    nombreCientifico: 'Avena sativa',
    familia: 'Poaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Cereal de clima frío cultivado por su grano nutritivo. Se usa en hojuelas, harina y como forraje.',
    temporada: 'Mayo - Julio',
    tipoDeSuelo: 'Franco, tolera suelos ácidos.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Roya de la corona, carbón.',
    imageUrl: 'https://images.pexels.com/photos/2072449/pexels-photo-2072449.jpeg',
    dataAiHint: 'oat field'
  },

  // 🥔 Tubérculos y raíces
  { 
    id: '7', 
    nombre: 'Papa Criolla',
    tipo: 'Tubérculos y raíces',
    nombreCientifico: 'Solanum phureja',
    familia: 'Solanaceae',
    region: 'Andina', 
    clima: 'Frío', 
    descripcionDetallada: 'Variedad de papa nativa de los Andes, de piel delgada y carne amarilla. Rápido crecimiento y cocción.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco arenoso, suelto y bien drenado.',
    tiempoSiembra: '3-4 semanas para brotar.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Gota, polilla guatemalteca.',
    imageUrl: 'https://images.pexels.com/photos/8690060/pexels-photo-8690060.jpeg', 
    dataAiHint: 'yellow potatoes'
  },
  {
    id: '8',
    nombre: 'Papa Pastusa',
    tipo: 'Tubérculos y raíces',
    nombreCientifico: 'Solanum tuberosum (Grupo Andigenum)',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Variedad de papa común en el sur de Colombia, ideal para sopas y purés por su textura harinosa.',
    temporada: 'Principalmente segundo semestre.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Siembra de tubérculos.',
    tiempoCosecha: '5-6 meses.',
    plagasComunes: 'Gota (Phytophthora infestans), gusano blanco.',
    imageUrl: 'https://images.pexels.com/photos/7194915/pexels-photo-7194915.jpeg',
    dataAiHint: 'potato harvest'
  },
  {
    id: '9',
    nombre: 'Papa Sabanera',
    tipo: 'Tubérculos y raíces',
    nombreCientifico: 'Solanum tuberosum (Grupo Andigenum)',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Papa de piel roja y carne blanca, firme, ideal para frituras y de buena conservación.',
    temporada: 'Variable, principalmente en Cundinamarca y Boyacá.',
    tipoDeSuelo: 'Franco, profundo y bien drenado.',
    tiempoSiembra: 'Siembra de tubérculos seleccionados.',
    tiempoCosecha: '6-7 meses.',
    plagasComunes: 'Gota, polilla guatemalteca, gusano blanco.',
    imageUrl: 'https://images.pexels.com/photos/70741/potatoes-vegetables-market-fresh-70741.jpeg',
    dataAiHint: 'red potatoes'
  },
  {
    id: '10',
    nombre: 'Yuca',
    tipo: 'Tubérculos y raíces',
    nombreCientifico: 'Manihot esculenta',
    familia: 'Euphorbiaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Raíz tuberosa fundamental en la dieta de zonas tropicales. Es tolerante a la sequía y a suelos pobres.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco-arenoso, bien drenado.',
    tiempoSiembra: 'Propagación por estacas.',
    tiempoCosecha: '8-12 meses.',
    plagasComunes: 'Ácaros, mosca blanca.',
    imageUrl: 'https://images.pexels.com/photos/10668434/pexels-photo-10668434.jpeg',
    dataAiHint: 'cassava root'
  },
  {
    id: '11',
    nombre: 'Ñame',
    tipo: 'Tubérculos y raíces',
    nombreCientifico: 'Dioscorea spp.',
    familia: 'Dioscoreaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Tubérculo de gran importancia en la costa Caribe. Requiere tutores para su crecimiento trepador.',
    temporada: 'Abril - Mayo',
    tipoDeSuelo: 'Franco, profundo y rico en materia orgánica.',
    tiempoSiembra: 'Siembra de trozos del tubérculo.',
    tiempoCosecha: '8-10 meses.',
    plagasComunes: 'Antracnosis, cochinillas.',
    imageUrl: 'https://images.pexels.com/photos/6945532/pexels-photo-6945532.jpeg',
    dataAiHint: 'yam root'
  },
  {
    id: '12',
    nombre: 'Arracacha',
    tipo: 'Tubérculos y raíces',
    nombreCientifico: 'Arracacia xanthorrhiza',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Raíz andina de sabor dulce y anisado, utilizada en sopas y purés. Se cultiva entre 1,800 y 2,500 msnm.',
    temporada: 'Marzo - Mayo',
    tipoDeSuelo: 'Franco, suelto y bien drenado.',
    tiempoSiembra: 'Propagación por cormos.',
    tiempoCosecha: '10-14 meses.',
    plagasComunes: 'Gusanos trozadores, nematodos.',
    imageUrl: 'https://images.pexels.com/photos/8438994/pexels-photo-8438994.jpeg',
    dataAiHint: 'arracacha root'
  },
  {
    id: '13',
    nombre: 'Batata',
    tipo: 'Tubérculos y raíces',
    nombreCientifico: 'Ipomoea batatas',
    familia: 'Convolvulaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Raíz tuberosa dulce, rica en vitaminas. Es una planta rastrera que cubre el suelo rápidamente.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco-arenoso, bien drenado.',
    tiempoSiembra: 'Por esquejes de tallo (bejucos).',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Gorgojo de la batata, nematodos.',
    imageUrl: 'https://images.pexels.com/photos/1299443/pexels-photo-1299443.jpeg',
    dataAiHint: 'sweet potato'
  },
  {
    id: '14',
    nombre: 'Oca',
    tipo: 'Tubérculos y raíces',
    nombreCientifico: 'Oxalis tuberosa',
    familia: 'Oxalidaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Tubérculo andino con una amplia gama de colores y un sabor ligeramente ácido que se reduce al exponerlo al sol.',
    temporada: 'Agosto - Septiembre.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Siembra de tubérculos.',
    tiempoCosecha: '7-8 meses.',
    plagasComunes: 'Gusano de la oca, mildeo.',
    imageUrl: 'https://images.pexels.com/photos/1359325/pexels-photo-1359325.jpeg',
    dataAiHint: 'oca tubers'
  },
  
  // 🫘 Leguminosas y oleaginosas
  {
    id: '15',
    nombre: 'Frijol Cargamanto',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Phaseolus vulgaris',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Variedad de frijol grande y de color rojo moteado, fundamental en platos típicos como la bandeja paisa.',
    temporada: 'Variable, dos ciclos al año.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses (seco).',
    plagasComunes: 'Antracnosis, mosca blanca.',
    imageUrl: 'https://images.pexels.com/photos/1059816/pexels-photo-1059816.jpeg',
    dataAiHint: 'cranberry beans'
  },
  {
    id: '16',
    nombre: 'Frijol Rojal',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Phaseolus vulgaris',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Variedad de frijol de grano rojo y pequeño, de cocción más rápida que el cargamanto. Muy consumido en el centro del país.',
    temporada: 'Variable, dos ciclos al año.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3 meses (seco).',
    plagasComunes: 'Mosaico común del frijol, áfidos.',
    imageUrl: 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg',
    dataAiHint: 'red kidney beans'
  },
  {
    id: '17',
    nombre: 'Frijol Verde',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Phaseolus vulgaris',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Se consume la vaina tierna antes de que los granos maduren. Cultivo de ciclo corto.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Suelos francos y ricos en materia orgánica.',
    tiempoSiembra: 'Siembra directa, requiere soporte (tutorado).',
    tiempoCosecha: '2-3 meses.',
    plagasComunes: 'Pulgones, babosas.',
    imageUrl: 'https://images.pexels.com/photos/128411/pexels-photo-128411.jpeg',
    dataAiHint: 'green beans'
  },
  {
    id: '18',
    nombre: 'Soya',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Glycine max',
    familia: 'Fabaceae',
    region: 'Orinoquía',
    clima: 'Cálido',
    descripcionDetallada: 'Oleaginosa de gran importancia industrial para la producción de aceite y torta de soya para alimento animal.',
    temporada: 'Primer y segundo semestre.',
    tipoDeSuelo: 'Franco-arcilloso, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Chinches, gusano cogollero.',
    imageUrl: 'https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg',
    dataAiHint: 'soybean field'
  },
  {
    id: '19',
    nombre: 'Lenteja',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Lens culinaris',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Leguminosa de grano pequeño y alto valor nutritivo. Colombia importa la mayor parte de su consumo.',
    temporada: 'Mayo - Junio.',
    tipoDeSuelo: 'Franco, bien drenado, tolera suelos pobres.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Pulgones, gorgojos.',
    imageUrl: 'https://images.pexels.com/photos/54123/pexels-photo-54123.jpeg',
    dataAiHint: 'lentil plant'
  },
  {
    id: '20',
    nombre: 'Garbanzo',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Cicer arietinum',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Leguminosa resistente a la sequía, cultivada por sus granos. Requiere climas secos durante la maduración.',
    temporada: 'Agosto - Septiembre.',
    tipoDeSuelo: 'Franco-arenoso, buen drenaje.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Rabia del garbanzo, mosca minadora.',
    imageUrl: 'https://images.pexels.com/photos/2093086/pexels-photo-2093086.jpeg',
    dataAiHint: 'chickpea plant'
  },
  {
    id: '21',
    nombre: 'Maní',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Arachis hypogaea',
    familia: 'Fabaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Leguminosa cuyo fruto crece bajo tierra. Requiere suelos sueltos para que el gineceo pueda penetrar en el suelo.',
    temporada: 'Abril - Mayo.',
    tipoDeSuelo: 'Arenoso o franco-arenoso, suelto.',
    tiempoSiembra: 'Siembra directa de semillas.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Gusano del maní, áfidos.',
    imageUrl: 'https://images.pexels.com/photos/162520/peanuts-nuts-seeds-red-162520.jpeg',
    dataAiHint: 'peanut plant'
  },
  {
    id: '22',
    nombre: 'Guisante (Arveja)',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Pisum sativum',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Leguminosa cultivada por sus semillas verdes. Las variedades trepadoras necesitan soporte.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mildeo polvoroso, trips de la arveja.',
    imageUrl: 'https://images.pexels.com/photos/5945731/pexels-photo-5945731.jpeg',
    dataAiHint: 'pea plant'
  },
  {
    id: '23',
    nombre: 'Haba',
    tipo: 'Leguminosas y oleaginosas',
    nombreCientifico: 'Vicia faba',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Leguminosa robusta de climas fríos, cultivada por sus grandes semillas. Fija nitrógeno en el suelo.',
    temporada: 'Mayo - Julio.',
    tipoDeSuelo: 'Franco-arcilloso, tolera suelos pesados.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '5-6 meses.',
    plagasComunes: 'Pulgón negro, mancha chocolate.',
    imageUrl: 'https://images.pexels.com/photos/769969/pexels-photo-769969.jpeg',
    dataAiHint: 'fava bean'
  },

  // ☕ Cultivos industriales y de exportación
  { 
    id: '24', 
    nombre: 'Café Arábigo',
    tipo: 'Cultivos industriales y de exportación',
    nombreCientifico: 'Coffea arabica',
    familia: 'Rubiaceae',
    region: 'Andina', 
    clima: 'Templado', 
    descripcionDetallada: 'La especie de café más cultivada en Colombia, famosa por su acidez y complejidad de sabor. Crece en laderas de montañas con sombra parcial.',
    temporada: 'Septiembre - Diciembre',
    tipoDeSuelo: 'Volcánico, profundo y con buen drenaje.',
    tiempoSiembra: '6-12 meses en vivero antes de trasplantar.',
    tiempoCosecha: '3-4 años para la primera cosecha.',
    plagasComunes: 'Broca del café, roya.',
    imageUrl: 'https://images.pexels.com/photos/1695050/pexels-photo-1695050.jpeg',
    dataAiHint: 'coffee plant'
  },
  { 
    id: '25', 
    nombre: 'Café Robusta',
    tipo: 'Cultivos industriales y de exportación',
    nombreCientifico: 'Coffea canephora',
    familia: 'Rubiaceae',
    region: 'Orinoquía', 
    clima: 'Cálido', 
    descripcionDetallada: 'Especie de café más resistente a enfermedades y altas temperaturas, con mayor contenido de cafeína. Usado para café instantáneo.',
    temporada: 'Variable, depende de la región.',
    tipoDeSuelo: 'Se adapta a diversos suelos, pero prefiere los bien drenados.',
    tiempoSiembra: 'Propagación por clones o semillas.',
    tiempoCosecha: '2-3 años para la primera cosecha.',
    plagasComunes: 'Broca del café, nematodos.',
    imageUrl: 'https://images.pexels.com/photos/1483398/pexels-photo-1483398.jpeg',
    dataAiHint: 'robusta coffee'
  },
  {
    id: '26',
    nombre: 'Caña de Azúcar',
    tipo: 'Cultivos industriales y de exportación',
    nombreCientifico: 'Saccharum officinarum',
    familia: 'Poaceae',
    region: 'Andina',
    clima: 'Cálido',
    descripcionDetallada: 'Cultivo industrial clave para la producción de azúcar y etanol. Requiere altas temperaturas y abundante agua.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco a arcilloso, profundo.',
    tiempoSiembra: 'Propagación por esquejes (tallos).',
    tiempoCosecha: '12-16 meses.',
    plagasComunes: 'Diatraea (barrenador del tallo), carbón.',
    imageUrl: 'https://images.pexels.com/photos/4113936/pexels-photo-4113936.jpeg',
    dataAiHint: 'sugar cane'
  },
  {
    id: '27',
    nombre: 'Palma Africana',
    tipo: 'Cultivos industriales y de exportación',
    nombreCientifico: 'Elaeis guineensis',
    familia: 'Arecaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Palma cultivada extensivamente para la producción de aceite de palma, usado en alimentos y biocombustibles.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Suelos profundos, bien drenados.',
    tiempoSiembra: 'Vivero por 12-15 meses.',
    tiempoCosecha: '3-4 años para iniciar producción.',
    plagasComunes: 'Pudrición del cogollo, picudo de la palma.',
    imageUrl: 'https://images.pexels.com/photos/704799/pexels-photo-704799.jpeg',
    dataAiHint: 'oil palm'
  },
  {
    id: '28',
    nombre: 'Cacao',
    tipo: 'Cultivos industriales y de exportación',
    nombreCientifico: 'Theobroma cacao',
    familia: 'Malvaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Árbol de cuyo fruto se extrae el chocolate. Crece bajo sombra en selvas húmedas tropicales.',
    temporada: 'Abril - Junio',
    tipoDeSuelo: 'Franco arcilloso, rico en materia orgánica.',
    tiempoSiembra: '4-6 meses en vivero.',
    tiempoCosecha: '3-5 años para la primera cosecha.',
    plagasComunes: 'Monilia, escoba de bruja.',
    imageUrl: 'https://images.pexels.com/photos/4099355/pexels-photo-4099355.jpeg',
    dataAiHint: 'cacao pod'
  },
  {
    id: '29',
    nombre: 'Algodón',
    tipo: 'Cultivos industriales y de exportación',
    nombreCientifico: 'Gossypium hirsutum',
    familia: 'Malvaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Cultivo para la producción de fibra textil. Requiere un periodo seco para la apertura de las bellotas.',
    temporada: 'Agosto - Septiembre.',
    tipoDeSuelo: 'Franco a franco-arcilloso, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '5-6 meses.',
    plagasComunes: 'Picudo del algodonero, mosca blanca.',
    imageUrl: 'https://images.pexels.com/photos/7688979/pexels-photo-7688979.jpeg',
    dataAiHint: 'cotton plant'
  },
  {
    id: '30',
    nombre: 'Tabaco',
    tipo: 'Cultivos industriales y de exportación',
    nombreCientifico: 'Nicotiana tabacum',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Planta cultivada por sus hojas, las cuales se secan y fermentan para producir tabaco. Requiere suelos fértiles.',
    temporada: 'Variable, según la zona.',
    tipoDeSuelo: 'Franco-arenoso, bien drenado.',
    tiempoSiembra: 'Trasplante desde semilleros.',
    tiempoCosecha: '3-4 meses después del trasplante.',
    plagasComunes: 'Mosaico del tabaco, gusano del cuerno.',
    imageUrl: 'https://images.pexels.com/photos/9738989/pexels-photo-9738989.jpeg',
    dataAiHint: 'tobacco plant'
  },

  // 🍌 Frutas tropicales y andinas
  { 
    id: '31', 
    nombre: 'Banano',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Musa sapientum',
    familia: 'Musaceae',
    region: 'Caribe', 
    clima: 'Cálido', 
    descripcionDetallada: 'Una de las frutas de exportación más importantes de Colombia. Requiere mucho sol, agua y suelos ricos.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco, profundo y rico en materia orgánica.',
    tiempoSiembra: 'Se propaga por cormos o hijuelos.',
    tiempoCosecha: '9-12 meses después de la siembra.',
    plagasComunes: 'Picudo negro, Sigatoka negra.',
    imageUrl: 'https://images.pexels.com/photos/2116013/pexels-photo-2116013.jpeg',
    dataAiHint: 'banana tree'
  },
  { 
    id: '32', 
    nombre: 'Plátano',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Musa paradisiaca',
    familia: 'Musaceae',
    region: 'Andina', 
    clima: 'Templado', 
    descripcionDetallada: 'Base de la alimentación en Colombia. Necesita sol, agua constante y suelos muy ricos en materia orgánica.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco, profundo y rico en materia orgánica.',
    tiempoSiembra: 'Se propaga por cormos o hijuelos.',
    tiempoCosecha: '9-12 meses después de la siembra.',
    plagasComunes: 'Picudo negro, Moko.',
    imageUrl: 'https://images.pexels.com/photos/5966380/pexels-photo-5966380.jpeg',
    dataAiHint: 'plantain tree'
  },
  {
    id: '33',
    nombre: 'Piña',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Ananas comosus',
    familia: 'Bromeliaceae',
    region: 'Andina',
    clima: 'Cálido',
    descripcionDetallada: 'Fruta tropical de gran demanda. La planta es una bromelia terrestre que requiere suelos bien drenados y ácidos.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco-arenoso, ácido y con buen drenaje.',
    tiempoSiembra: 'Propagación por coronas o hijuelos.',
    tiempoCosecha: '18-24 meses.',
    plagasComunes: 'Cochinilla harinosa, barrenador del fruto.',
    imageUrl: 'https://images.pexels.com/photos/137119/pexels-photo-137119.jpeg',
    dataAiHint: 'pineapple plant'
  },
  { 
    id: '34', 
    nombre: 'Mango',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Mangifera indica',
    familia: 'Anacardiaceae',
    region: 'Caribe', 
    clima: 'Cálido', 
    descripcionDetallada: 'Árbol tropical que necesita pleno sol y mucho espacio. Una poda anual ayuda a mejorar la producción.',
    temporada: 'Mayo - Agosto',
    tipoDeSuelo: 'Profundo y bien drenado. Tolera varios tipos de suelo.',
    tiempoSiembra: 'Se propaga por injerto.',
    tiempoCosecha: '3-5 años para la primera cosecha.',
    plagasComunes: 'Mosca de la fruta, antracnosis.',
    imageUrl: 'https://images.pexels.com/photos/2754668/pexels-photo-2754668.jpeg',
    dataAiHint: 'mango tree'
  },
  { 
    id: '35', 
    nombre: 'Papaya',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Carica papaya',
    familia: 'Caricaceae',
    region: 'Orinoquía', 
    clima: 'Cálido', 
    descripcionDetallada: 'Planta de crecimiento rápido que produce frutos grandes y nutritivos. Sensible al encharcamiento y a los vientos fuertes.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco, profundo, rico en materia orgánica y con excelente drenaje.',
    tiempoSiembra: 'Por semilla.',
    tiempoCosecha: '9-12 meses.',
    plagasComunes: 'Ácaros, virus de la mancha anular.',
    imageUrl: 'https://images.pexels.com/photos/6945037/pexels-photo-6945037.jpeg',
    dataAiHint: 'papaya tree'
  },
  {
    id: '36',
    nombre: 'Maracuyá',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Passiflora edulis',
    familia: 'Passifloraceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Planta trepadora cuyo fruto ácido es muy apreciado para jugos y postres. Requiere espalderas o soporte.',
    temporada: 'Todo el año',
    tipoDeSuelo: 'Franco, bien drenado, rico en materia orgánica.',
    tiempoSiembra: 'Por semilla o esquejes.',
    tiempoCosecha: '6-9 meses.',
    plagasComunes: 'Mosca del ovario, secadera.',
    imageUrl: 'https://images.pexels.com/photos/4203063/pexels-photo-4203063.jpeg',
    dataAiHint: 'passion fruit'
  },
  {
    id: '37',
    nombre: 'Tomate de Árbol',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Solanum betaceum',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Arbusto que produce frutos ácidos, ideales para jugos. Se cultiva en zonas de clima frío moderado.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Por semilla o injerto.',
    tiempoCosecha: '1.5 - 2 años.',
    plagasComunes: 'Antracnosis, mosca de la fruta.',
    imageUrl: 'https://images.pexels.com/photos/10839077/pexels-photo-10839077.jpeg',
    dataAiHint: 'tree tomato'
  },
  {
    id: '38',
    nombre: 'Uchuva',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Physalis peruviana',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Fruta exótica de exportación, envuelta en un capacho protector. Arbusto que requiere buen drenaje.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco arenoso, bien drenado.',
    tiempoSiembra: 'Por semilla.',
    tiempoCosecha: '6-8 meses.',
    plagasComunes: 'Pulgones, mosca blanca.',
    imageUrl: 'https://images.pexels.com/photos/133615/pexels-photo-133615.jpeg',
    dataAiHint: 'cape gooseberry'
  },
  {
    id: '39',
    nombre: 'Mora',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Rubus glaucus',
    familia: 'Rosaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Arbusto espinoso que produce frutos ácidos muy populares para jugos y postres. Requiere podas regulares.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Por acodos o estacas.',
    tiempoCosecha: '1 año para iniciar producción.',
    plagasComunes: 'Mildeo velloso, mosca de la fruta.',
    imageUrl: 'https://images.pexels.com/photos/1359306/pexels-photo-1359306.jpeg',
    dataAiHint: 'blackberry bush'
  },
  {
    id: '40',
    nombre: 'Lulo',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Solanum quitoense',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Fruta andina de sabor exótico, muy usada en jugos. Planta arbustiva sensible a nematodos y plagas.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica, buen drenaje.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '6-8 meses.',
    plagasComunes: 'Nematodos, perforador del fruto.',
    imageUrl: 'https://images.pexels.com/photos/18258380/pexels-photo-18258380.jpeg',
    dataAiHint: 'lulo fruit'
  },
  {
    id: '41',
    nombre: 'Guayaba',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Psidium guajava',
    familia: 'Myrtaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Árbol rústico que produce una fruta muy aromática, rica en vitamina C. Se adapta a diversas condiciones.',
    temporada: 'Todo el año, con picos de cosecha.',
    tipoDeSuelo: 'Amplia adaptación, prefiere suelos bien drenados.',
    tiempoSiembra: 'Por semilla o acodo aéreo.',
    tiempoCosecha: '2-3 años.',
    plagasComunes: 'Mosca de la fruta, picudo de la guayaba.',
    imageUrl: 'https://images.pexels.com/photos/2668514/pexels-photo-2668514.jpeg',
    dataAiHint: 'guava tree'
  },
  {
    id: '42',
    nombre: 'Granadilla',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Passiflora ligularis',
    familia: 'Passifloraceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Fruta de la pasión de sabor dulce y aromático. Es una enredadera que necesita estructura de soporte.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, profundo y rico en materia orgánica.',
    tiempoSiembra: 'Por semilla.',
    tiempoCosecha: '10-12 meses.',
    plagasComunes: 'Pulgones, arañita roja.',
    imageUrl: 'https://images.pexels.com/photos/1809341/pexels-photo-1809341.jpeg',
    dataAiHint: 'sweet granadilla'
  },
  {
    id: '43',
    nombre: 'Pitahaya',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Selenicereus undatus',
    familia: 'Cactaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Fruta exótica producida por un cactus trepador. Requiere polinización (a menudo manual o nocturna) para fructificar.',
    temporada: 'Cosecha principal en primer semestre.',
    tipoDeSuelo: 'Franco-arenoso, muy buen drenaje.',
    tiempoSiembra: 'Por esquejes.',
    tiempoCosecha: '1 - 1.5 años.',
    plagasComunes: 'Pudrición del tallo, mosca de la fruta.',
    imageUrl: 'https://images.pexels.com/photos/2294477/pexels-photo-2294477.jpeg',
    dataAiHint: 'dragon fruit'
  },
  {
    id: '44',
    nombre: 'Uva',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Vitis vinifera',
    familia: 'Vitaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Cultivo de vid principalmente para producción de vino y uva de mesa en zonas específicas como Boyacá y Valle del Cauca.',
    temporada: 'Diciembre - Febrero.',
    tipoDeSuelo: 'Franco-arcilloso, buen drenaje.',
    tiempoSiembra: 'Por estacas o injertos.',
    tiempoCosecha: '2-3 años para la primera cosecha.',
    plagasComunes: 'Mildeo, oídio.',
    imageUrl: 'https://images.pexels.com/photos/1029243/pexels-photo-1029243.jpeg',
    dataAiHint: 'grape vine'
  },
  {
    id: '45',
    nombre: 'Naranja',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Citrus × sinensis',
    familia: 'Rutaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Cítrico de gran consumo. Los árboles requieren pleno sol y protección contra vientos fuertes.',
    temporada: 'Variable, picos de cosecha según la variedad.',
    tipoDeSuelo: 'Franco, profundo y bien drenado.',
    tiempoSiembra: 'Por injerto.',
    tiempoCosecha: '3-4 años.',
    plagasComunes: 'HLB, ácaros, minador de los cítricos.',
    imageUrl: 'https://images.pexels.com/photos/2090877/pexels-photo-2090877.jpeg',
    dataAiHint: 'orange tree'
  },
  {
    id: '46',
    nombre: 'Mandarina',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Citrus reticulata',
    familia: 'Rutaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Cítrico popular por su facilidad para pelar. Árbol más pequeño y tolerante al frío que el naranjo.',
    temporada: 'Variable, segundo semestre.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Por injerto.',
    tiempoCosecha: '2-3 años.',
    plagasComunes: 'Gomosis, mosca de la fruta.',
    imageUrl: 'https://images.pexels.com/photos/1001550/pexels-photo-1001550.jpeg',
    dataAiHint: 'tangerine tree'
  },
  {
    id: '47',
    nombre: 'Limón',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Citrus × limon',
    familia: 'Rutaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Cítrico ácido de uso extendido. La variedad Tahití es muy común en Colombia. Producción casi continua.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Por injerto o estacas.',
    tiempoCosecha: '2-3 años.',
    plagasComunes: 'HLB, minador de los cítricos.',
    imageUrl: 'https://images.pexels.com/photos/1253457/pexels-photo-1253457.jpeg',
    dataAiHint: 'lemon tree'
  },
  {
    id: '48',
    nombre: 'Coco',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Cocos nucifera',
    familia: 'Arecaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Palmera icónica de las costas tropicales, aprovechada integralmente (agua, pulpa, fibra).',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Arenoso, tolera alta salinidad.',
    tiempoSiembra: 'Siembra del fruto completo.',
    tiempoCosecha: '6-10 años.',
    plagasComunes: 'Anillo rojo, picudo de la palma.',
    imageUrl: 'https://images.pexels.com/photos/9609841/pexels-photo-9609841.jpeg',
    dataAiHint: 'coconut tree'
  },
  {
    id: '49',
    nombre: 'Sandía',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Citrullus lanatus',
    familia: 'Cucurbitaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Planta rastrera que produce frutos grandes y jugosos. Requiere mucho espacio, sol y calor.',
    temporada: 'Marzo - Mayo.',
    tipoDeSuelo: 'Franco-arenoso, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mildeo polvoso, pulgones.',
    imageUrl: 'https://images.pexels.com/photos/1313267/pexels-photo-1313267.jpeg',
    dataAiHint: 'watermelon patch'
  },
  {
    id: '50',
    nombre: 'Melón',
    tipo: 'Frutas tropicales y andinas',
    nombreCientifico: 'Cucumis melo',
    familia: 'Cucurbitaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Fruta dulce y aromática de una planta rastrera que necesita climas secos y cálidos para un buen desarrollo del fruto.',
    temporada: 'Febrero - Abril.',
    tipoDeSuelo: 'Franco, bien drenado, rico en materia orgánica.',
    tiempoSiembra: 'Siembra directa o trasplante.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mildeo velloso, mosca minadora.',
    imageUrl: 'https://images.pexels.com/photos/5945842/pexels-photo-5945842.jpeg',
    dataAiHint: 'melon patch'
  },

  // 🥬 Hortalizas
  {
    id: '51',
    nombre: 'Tomate de Mesa',
    tipo: 'Hortalizas',
    nombreCientifico: 'Solanum lycopersicum',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de fruto más cultivada a nivel mundial. Requiere tutorado para mantener la planta erguida y ventilada.',
    temporada: 'Todo el año (en invernadero).',
    tipoDeSuelo: 'Franco, rico en materia orgánica, buen drenaje.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mosca blanca, tuta absoluta, gota.',
    imageUrl: 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg',
    dataAiHint: 'tomato plant'
  },
  {
    id: '52',
    nombre: 'Cebolla Cabezona',
    tipo: 'Hortalizas',
    nombreCientifico: 'Allium cepa',
    familia: 'Amaryllidaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Hortaliza de bulbo indispensable en la cocina. El curado al sol tras la cosecha es clave para su conservación.',
    temporada: 'Variable.',
    tipoDeSuelo: 'Franco, suelto y bien drenado.',
    tiempoSiembra: 'Trasplante o siembra directa.',
    tiempoCosecha: '4-6 meses.',
    plagasComunes: 'Mildeo velloso, trips.',
    imageUrl: 'https://images.pexels.com/photos/144244/onions-vegetables-market-sacks-144244.jpeg',
    dataAiHint: 'onion patch'
  },
  {
    id: '53',
    nombre: 'Cebolla Larga',
    tipo: 'Hortalizas',
    nombreCientifico: 'Allium fistulosum',
    familia: 'Amaryllidaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Variedad de cebolla que no forma bulbo, se consume su tallo. Cultivo muy común en huertas familiares.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Por división de matas o semilla.',
    tiempoCosecha: '4-6 meses.',
    plagasComunes: 'Roya, trips.',
    imageUrl: 'https://images.pexels.com/photos/4117923/pexels-photo-4117923.jpeg',
    dataAiHint: 'scallion patch'
  },
  {
    id: '54',
    nombre: 'Zanahoria',
    tipo: 'Hortalizas',
    nombreCientifico: 'Daucus carota',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de raíz muy popular. Requiere suelos sueltos y profundos para el correcto desarrollo de la raíz.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco-arenoso, profundo y sin piedras.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mosca de la zanahoria, nematodos.',
    imageUrl: 'https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg',
    dataAiHint: 'carrot patch'
  },
  {
    id: '55',
    nombre: 'Lechuga',
    tipo: 'Hortalizas',
    nombreCientifico: 'Lactuca sativa',
    familia: 'Asteraceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de hoja de ciclo corto. Sensible al calor, que puede inducir una floración prematura (subida a flor).',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Siembra directa o trasplante.',
    tiempoCosecha: '2-3 meses.',
    plagasComunes: 'Pulgones, babosas, mildeo velloso.',
    imageUrl: 'https://images.pexels.com/photos/2893635/pexels-photo-2893635.jpeg',
    dataAiHint: 'lettuce patch'
  },
  {
    id: '56',
    nombre: 'Repollo',
    tipo: 'Hortalizas',
    nombreCientifico: 'Brassica oleracea var. capitata',
    familia: 'Brassicaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Hortaliza de hoja que forma una cabeza compacta. Prefiere climas frescos para una buena formación.',
    temporada: 'Todo el año, mejor en clima fresco.',
    tipoDeSuelo: 'Franco, rico en materia orgánica y nitrógeno.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Mariposa blanca de la col, hernia de las coles.',
    imageUrl: 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg',
    dataAiHint: 'cabbage patch'
  },
  {
    id: '57',
    nombre: 'Ajo',
    tipo: 'Hortalizas',
    nombreCientifico: 'Allium sativum',
    familia: 'Amaryllidaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de bulbo (compuesto por dientes). Requiere un periodo de frío para la formación del bulbo.',
    temporada: 'Siembra en meses fríos.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Plantación de dientes individuales.',
    tiempoCosecha: '6-8 meses.',
    plagasComunes: 'Roya, nematodos del tallo.',
    imageUrl: 'https://images.pexels.com/photos/161556/garlic-vegetables-food-fresh-161556.jpeg',
    dataAiHint: 'garlic plant'
  },
  {
    id: '58',
    nombre: 'Pepino',
    tipo: 'Hortalizas',
    nombreCientifico: 'Cucumis sativus',
    familia: 'Cucurbitaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Planta trepadora o rastrera que produce frutos refrescantes. Requiere tutorado para mejor calidad de fruto.',
    temporada: 'Todo el año en clima adecuado.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Siembra directa o trasplante.',
    tiempoCosecha: '2-3 meses.',
    plagasComunes: 'Mildeo polvoso, araña roja.',
    imageUrl: 'https://images.pexels.com/photos/2329440/pexels-photo-2329440.jpeg',
    dataAiHint: 'cucumber plant'
  },
  {
    id: '59',
    nombre: 'Habichuela',
    tipo: 'Hortalizas',
    nombreCientifico: 'Phaseolus vulgaris',
    familia: 'Fabaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Similar al frijol verde, se consume la vaina. Las variedades de enrame necesitan tutores.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '2-3 meses.',
    plagasComunes: 'Pulgones, mosca blanca.',
    imageUrl: 'https://images.pexels.com/photos/264537/pexels-photo-264537.jpeg',
    dataAiHint: 'string bean'
  },
  {
    id: '60',
    nombre: 'Brócoli',
    tipo: 'Hortalizas',
    nombreCientifico: 'Brassica oleracea var. italica',
    familia: 'Brassicaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Hortaliza de la que se consume la inflorescencia inmadura. Prefiere climas frescos.',
    temporada: 'Siembra en épocas frescas.',
    tipoDeSuelo: 'Franco-arcilloso, rico en materia orgánica.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Pulgón de la col, mariposa blanca.',
    imageUrl: 'https://images.pexels.com/photos/47347/broccoli-vegetable-food-healthy-47347.jpeg',
    dataAiHint: 'broccoli plant'
  },
  {
    id: '61',
    nombre: 'Coliflor',
    tipo: 'Hortalizas',
    nombreCientifico: 'Brassica oleracea var. botrytis',
    familia: 'Brassicaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Similar al brócoli, pero forma una pella blanca y compacta. Sensible a altas temperaturas.',
    temporada: 'Siembra en épocas frescas.',
    tipoDeSuelo: 'Franco, profundo y rico en boro.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Hernia de la col, pulgones.',
    imageUrl: 'https://images.pexels.com/photos/162866/vegetables-cauliflower-food-diet-162866.jpeg',
    dataAiHint: 'cauliflower plant'
  },
  {
    id: '62',
    nombre: 'Espinaca',
    tipo: 'Hortalizas',
    nombreCientifico: 'Spinacia oleracea',
    familia: 'Amaranthaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Hortaliza de hoja de rápido crecimiento y alto contenido de hierro. Prefiere climas frescos para evitar la floración prematura.',
    temporada: 'Todo el año en clima frío.',
    tipoDeSuelo: 'Franco, rico en nitrógeno.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '45-60 días.',
    plagasComunes: 'Mildeo velloso, pulgones.',
    imageUrl: 'https://images.pexels.com/photos/2325843/pexels-photo-2325843.jpeg',
    dataAiHint: 'spinach patch'
  },
  {
    id: '63',
    nombre: 'Pimentón',
    tipo: 'Hortalizas',
    nombreCientifico: 'Capsicum annuum',
    familia: 'Solanaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Fruto hueco de paredes carnosas. Requiere temperaturas cálidas y buena exposición solar.',
    temporada: 'Todo el año bajo cubierta.',
    tipoDeSuelo: 'Franco-arenoso, rico en materia orgánica.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Ácaros, mosca blanca, trips.',
    imageUrl: 'https://images.pexels.com/photos/1879061/pexels-photo-1879061.jpeg',
    dataAiHint: 'bell pepper'
  },
  {
    id: '64',
    nombre: 'Berenjena',
    tipo: 'Hortalizas',
    nombreCientifico: 'Solanum melongena',
    familia: 'Solanaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Planta que requiere calor y sol para producir sus frutos morados y brillantes. Sensible al frío.',
    temporada: 'Siembra en temporada cálida.',
    tipoDeSuelo: 'Franco, profundo y rico en materia orgánica.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Araña roja, escarabajo de la patata.',
    imageUrl: 'https://images.pexels.com/photos/1459330/pexels-photo-1459330.jpeg',
    dataAiHint: 'eggplant plant'
  },
  {
    id: '65',
    nombre: 'Rábano',
    tipo: 'Hortalizas',
    nombreCientifico: 'Raphanus sativus',
    familia: 'Brassicaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de raíz de ciclo muy corto. Ideal para siembras sucesivas y huertos pequeños.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Suelto, arenoso y fresco.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '30-45 días.',
    plagasComunes: 'Pulgones, gusanos grises.',
    imageUrl: 'https://images.pexels.com/photos/1656666/pexels-photo-1656666.jpeg',
    dataAiHint: 'radish patch'
  },
  {
    id: '66',
    nombre: 'Apio',
    tipo: 'Hortalizas',
    nombreCientifico: 'Apium graveolens',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hortaliza de la que se consumen las pencas (tallos). Requiere mucha agua y suelos ricos.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, húmedo y rico en materia orgánica.',
    tiempoSiembra: 'Trasplante desde semillero.',
    tiempoCosecha: '4-5 meses.',
    plagasComunes: 'Septoriosis, mosca del apio.',
    imageUrl: 'https://images.pexels.com/photos/5946969/pexels-photo-5946969.jpeg',
    dataAiHint: 'celery plant'
  },
  {
    id: '67',
    nombre: 'Calabacín',
    tipo: 'Hortalizas',
    nombreCientifico: 'Cucurbita pepo',
    familia: 'Cucurbitaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Planta de crecimiento rápido y alta producción. Se cosecha el fruto tierno.',
    temporada: 'Siembra en clima cálido.',
    tipoDeSuelo: 'Franco, bien abonado y con buen drenaje.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '40-60 días.',
    plagasComunes: 'Oídio, pulgones.',
    imageUrl: 'https://images.pexels.com/photos/8992923/pexels-photo-8992923.jpeg',
    dataAiHint: 'zucchini plant'
  },

  // 🌷 Flores / Ornamentales
  {
    id: '68',
    nombre: 'Rosa',
    tipo: 'Flores / Ornamentales',
    nombreCientifico: 'Rosa spp.',
    familia: 'Rosaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Una de las flores de exportación más importantes de Colombia. Se cultiva bajo invernadero en la Sabana de Bogotá.',
    temporada: 'Producción continua.',
    tipoDeSuelo: 'Franco-arcilloso, rico y bien drenado.',
    tiempoSiembra: 'Propagación por esquejes o injertos.',
    tiempoCosecha: 'La producción inicia a los 4-6 meses.',
    plagasComunes: 'Ácaros, mildeo polvoso, botrytis.',
    imageUrl: 'https://images.pexels.com/photos/39517/rose-flower-blossom-bloom-39517.jpeg',
    dataAiHint: 'rose garden'
  },
  {
    id: '69',
    nombre: 'Clavel',
    tipo: 'Flores / Ornamentales',
    nombreCientifico: 'Dianthus caryophyllus',
    familia: 'Caryophyllaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Flor de corte de gran tradición y volumen de exportación. Requiere desbotones para obtener una flor principal de calidad.',
    temporada: 'Producción continua.',
    tipoDeSuelo: 'Franco-arenoso, con buen drenaje y pH neutro.',
    tiempoSiembra: 'Propagación por esquejes.',
    tiempoCosecha: 'La producción inicia a los 5-6 meses.',
    plagasComunes: 'Trips, roya, fusarium.',
    imageUrl: 'https://images.pexels.com/photos/4505963/pexels-photo-4505963.jpeg',
    dataAiHint: 'carnation flowers'
  },
  {
    id: '70',
    nombre: 'Crisantemo',
    tipo: 'Flores / Ornamentales',
    nombreCientifico: 'Chrysanthemum spp.',
    familia: 'Asteraceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Flor muy popular para arreglos, con gran diversidad de formas y colores. Su floración es controlada por el fotoperiodo.',
    temporada: 'Producción continua controlada.',
    tipoDeSuelo: 'Franco, bien drenado y rico en materia orgánica.',
    tiempoSiembra: 'Propagación por esquejes.',
    tiempoCosecha: '3-4 meses desde el esqueje.',
    plagasComunes: 'Roya blanca, áfidos, trips.',
    imageUrl: 'https://images.pexels.com/photos/112285/pexels-photo-112285.jpeg',
    dataAiHint: 'chrysanthemum flowers'
  },
  {
    id: '71',
    nombre: 'Astromelia (Alstroemeria)',
    tipo: 'Flores / Ornamentales',
    nombreCientifico: 'Alstroemeria spp.',
    familia: 'Alstroemeriaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Flor de corte muy duradera y apreciada en la exportación, conocida como "Lirio de los Incas".',
    temporada: 'Producción continua.',
    tipoDeSuelo: 'Franco-arenoso, suelto y con buen drenaje.',
    tiempoSiembra: 'Propagación por división de rizomas.',
    tiempoCosecha: 'Producción inicia a los 6-8 meses.',
    plagasComunes: 'Trips, babosas.',
    imageUrl: 'https://images.pexels.com/photos/8276949/pexels-photo-8276949.jpeg',
    dataAiHint: 'alstroemeria flowers'
  },
  {
    id: '72',
    nombre: 'Gerbera',
    tipo: 'Flores / Ornamentales',
    nombreCientifico: 'Gerbera jamesonii',
    familia: 'Asteraceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Flor tipo margarita de colores vivos y tallo largo. Muy usada en decoración y ramos.',
    temporada: 'Producción continua.',
    tipoDeSuelo: 'Arenoso, con excelente drenaje y aireación.',
    tiempoSiembra: 'Propagación por división de matas o in vitro.',
    tiempoCosecha: 'Producción inicia a los 4-5 meses.',
    plagasComunes: 'Mosca blanca, minador de la hoja.',
    imageUrl: 'https://images.pexels.com/photos/736230/pexels-photo-736230.jpeg',
    dataAiHint: 'gerbera daisy'
  },
  {
    id: '73',
    nombre: 'Orquídea',
    tipo: 'Flores / Ornamentales',
    nombreCientifico: 'Cattleya trianae (y otras)',
    familia: 'Orchidaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Flor nacional de Colombia. Muchas son epífitas, por lo que crecen sobre los árboles y no en tierra.',
    temporada: 'Variable según la especie.',
    tipoDeSuelo: 'Sustrato a base de corteza, no suelo común.',
    tiempoSiembra: 'Propagación por división de pseudobulbos.',
    tiempoCosecha: ' ornamental, no aplica cosecha.',
    plagasComunes: 'Cochinillas, pulgones.',
    imageUrl: 'https://images.pexels.com/photos/1018659/pexels-photo-1018659.jpeg',
    dataAiHint: 'orchid flower'
  },
  {
    id: '74',
    nombre: 'Gladiolo',
    tipo: 'Flores / Ornamentales',
    nombreCientifico: 'Gladiolus spp.',
    familia: 'Iridaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Planta bulbosa que produce una espiga floral alta y vistosa. Usada como flor de corte.',
    temporada: 'Siembra escalonada para producción continua.',
    tipoDeSuelo: 'Franco-arenoso, bien drenado.',
    tiempoSiembra: 'Plantación de cormos (bulbos).',
    tiempoCosecha: 'La floración ocurre a los 3-4 meses.',
    plagasComunes: 'Trips, roya del gladiolo.',
    imageUrl: 'https://images.pexels.com/photos/1400249/pexels-photo-1400249.jpeg',
    dataAiHint: 'gladiolus flowers'
  },
  
  // 🪴 Aromáticas / Medicinales / Especias
  {
    id: '75',
    nombre: 'Orégano',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Origanum vulgare',
    familia: 'Lamiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hierba aromática perenne muy utilizada en la cocina mediterránea. Prefiere climas secos y soleados.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Suelto, bien drenado, incluso pobre.',
    tiempoSiembra: 'Por semilla, esqueje o división de mata.',
    tiempoCosecha: 'Cosecha continua de hojas.',
    plagasComunes: 'Pulgones, araña roja.',
    imageUrl: 'https://images.pexels.com/photos/1618907/pexels-photo-1618907.jpeg',
    dataAiHint: 'oregano plant'
  },
  {
    id: '76',
    nombre: 'Albahaca',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Ocimum basilicum',
    familia: 'Lamiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Planta aromática anual muy sensible al frío. Se deben cortar las flores para prolongar la producción de hojas.',
    temporada: 'Siembra en temporada cálida.',
    tipoDeSuelo: 'Fértil, húmedo pero bien drenado.',
    tiempoSiembra: 'Por semilla.',
    tiempoCosecha: 'Cosecha de hojas a partir de los 2-3 meses.',
    plagasComunes: 'Mildeo, caracoles.',
    imageUrl: 'https://images.pexels.com/photos/1618912/pexels-photo-1618912.jpeg',
    dataAiHint: 'basil plant'
  },
  {
    id: '77',
    nombre: 'Hierbabuena',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Mentha spicata',
    familia: 'Lamiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hierba perenne muy invasiva, de aroma refrescante. Fácil de cultivar.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Húmedo y rico en materia orgánica.',
    tiempoSiembra: 'Por esquejes o división de estolones.',
    tiempoCosecha: 'Cosecha continua.',
    plagasComunes: 'Roya, mildeo polvoroso.',
    imageUrl: 'https://images.pexels.com/photos/326240/pexels-photo-326240.jpeg',
    dataAiHint: 'spearmint plant'
  },
  {
    id: '78',
    nombre: 'Manzanilla',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Matricaria recutita',
    familia: 'Asteraceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Hierba medicinal muy popular por sus propiedades calmantes. Se utilizan sus flores para infusiones.',
    temporada: 'Siembra en primavera.',
    tipoDeSuelo: 'Bien drenado, no muy exigente.',
    tiempoSiembra: 'Siembra directa o trasplante.',
    tiempoCosecha: 'Las flores se cosechan a los 2-3 meses.',
    plagasComunes: 'Pulgones.',
    imageUrl: 'https://images.pexels.com/photos/1324311/pexels-photo-1324311.jpeg',
    dataAiHint: 'chamomile flowers'
  },
  {
    id: '79',
    nombre: 'Cilantro',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Coriandrum sativum',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hierba aromática indispensable en la cocina colombiana. De rápido crecimiento y sensible al calor excesivo.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, suelto y con buen drenaje.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '40-60 días.',
    plagasComunes: 'Pulgones, hongos foliares.',
    imageUrl: 'https://images.pexels.com/photos/162804/herbs-coriander-green-spicy-162804.jpeg',
    dataAiHint: 'coriander plant'
  },
  {
    id: '80',
    nombre: 'Perejil',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Petroselinum crispum',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Hierba bienal cultivada como anual, muy usada como condimento. Germinación lenta.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Fértil, profundo y húmedo.',
    tiempoSiembra: 'Siembra directa, remojar semillas antes.',
    tiempoCosecha: 'Cosecha de hojas a los 3 meses.',
    plagasComunes: 'Mosca del apio, septoriosis.',
    imageUrl: 'https://images.pexels.com/photos/162806/herbs-parsley-green-spicy-162806.jpeg',
    dataAiHint: 'parsley plant'
  },
  {
    id: '81',
    nombre: 'Jengibre',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Zingiber officinale',
    familia: 'Zingiberaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Planta cuyo rizoma (tallo subterráneo) es muy apreciado como especia y medicinal. Prefiere sombra parcial.',
    temporada: 'Inicio de la temporada de lluvias.',
    tipoDeSuelo: 'Franco, rico en materia orgánica, bien drenado.',
    tiempoSiembra: 'Plantación de trozos del rizoma.',
    tiempoCosecha: '8-10 meses.',
    plagasComunes: 'Bacteriosis, nematodos.',
    imageUrl: 'https://images.pexels.com/photos/1327814/pexels-photo-1327814.jpeg',
    dataAiHint: 'ginger plant'
  },
  {
    id: '82',
    nombre: 'Cúrcuma',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Curcuma longa',
    familia: 'Zingiberaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Planta emparentada con el jengibre, de cuyo rizoma se obtiene el colorante y especia del mismo nombre.',
    temporada: 'Inicio de la temporada de lluvias.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Plantación de trozos del rizoma.',
    tiempoCosecha: '9-10 meses.',
    plagasComunes: 'Pudrición del rizoma.',
    imageUrl: 'https://images.pexels.com/photos/3434523/pexels-photo-3434523.jpeg',
    dataAiHint: 'turmeric plant'
  },
  {
    id: '83',
    nombre: 'Achiote',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Bixa orellana',
    familia: 'Bixaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Arbusto de cuyas semillas se extrae un colorante natural rojizo-amarillento muy usado en la gastronomía latinoamericana.',
    temporada: 'Variable.',
    tipoDeSuelo: 'Se adapta bien a diferentes suelos.',
    tiempoSiembra: 'Por semilla.',
    tiempoCosecha: 'Producción a los 2 años.',
    plagasComunes: 'Generalmente resistente a plagas.',
    imageUrl: 'https://images.pexels.com/photos/8949826/pexels-photo-8949826.jpeg',
    dataAiHint: 'annatto tree'
  },
  {
    id: '84',
    nombre: 'Anís',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Pimpinella anisum',
    familia: 'Apiaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Planta anual cultivada por sus semillas aromáticas, usadas en confitería, panadería y licores.',
    temporada: 'Primavera.',
    tipoDeSuelo: 'Ligero, fértil y bien drenado.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '4-5 meses, cuando las semillas maduran.',
    plagasComunes: 'Pulgones.',
    imageUrl: 'https://images.pexels.com/photos/61127/anise-star-anise-spices-food-61127.jpeg',
    dataAiHint: 'anise plant'
  },
  {
    id: '85',
    nombre: 'Vainilla',
    tipo: 'Aromáticas / Medicinales / Especias',
    nombreCientifico: 'Vanilla planifolia',
    familia: 'Orchidaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Orquídea trepadora de la que se obtiene uno de los saborizantes más apreciados del mundo. Requiere polinización manual.',
    temporada: 'Floración específica, polinización manual.',
    tipoDeSuelo: 'Sustrato rico en materia orgánica, poroso.',
    tiempoSiembra: 'Por esquejes.',
    tiempoCosecha: 'Las vainas se cosechan 8-9 meses tras polinizar.',
    plagasComunes: 'Pudrición de raíces, antracnosis.',
    imageUrl: 'https://images.pexels.com/photos/45203/brown-fragrance-chocolate-anise-45203.jpeg',
    dataAiHint: 'vanilla orchid'
  },

  // 🌱 Otros peculiares o emergentes
  {
    id: '86',
    nombre: 'Quinua',
    tipo: 'Otros peculiares o emergentes',
    nombreCientifico: 'Chenopodium quinoa',
    familia: 'Amaranthaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Pseudocereal andino de alto valor nutricional. Adaptado a condiciones de altura y suelos marginales.',
    temporada: 'Abril - Mayo.',
    tipoDeSuelo: 'Franco-arenoso, tolera salinidad.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '5-7 meses.',
    plagasComunes: 'Mildeo, polillas.',
    imageUrl: 'https://images.pexels.com/photos/176840/pexels-photo-176840.jpeg',
    dataAiHint: 'quinoa field'
  },
  {
    id: '87',
    nombre: 'Amaranto',
    tipo: 'Otros peculiares o emergentes',
    nombreCientifico: 'Amaranthus caudatus',
    familia: 'Amaranthaceae',
    region: 'Andina',
    clima: 'Templado',
    descripcionDetallada: 'Pseudocereal de alto valor proteico, cuyas hojas también son comestibles. Muy resistente a la sequía.',
    temporada: 'Siembra en clima cálido.',
    tipoDeSuelo: 'Adaptable, prefiere suelos bien drenados.',
    tiempoSiembra: 'Siembra directa.',
    tiempoCosecha: '3-4 meses.',
    plagasComunes: 'Pulgones, gusanos.',
    imageUrl: 'https://images.pexels.com/photos/1230438/pexels-photo-1230438.jpeg',
    dataAiHint: 'amaranth plant'
  },
  {
    id: '88',
    nombre: 'Aloe Vera',
    tipo: 'Otros peculiares o emergentes',
    nombreCientifico: 'Aloe barbadensis miller',
    familia: 'Asphodelaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Planta suculenta conocida por el gel de sus hojas, con usos medicinales y cosméticos. No tolera el exceso de agua.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Arenoso, con excelente drenaje.',
    tiempoSiembra: 'Propagación por hijuelos.',
    tiempoCosecha: 'Las hojas se cosechan a partir de los 2 años.',
    plagasComunes: 'Cochinilla algodonosa, pudrición de raíz.',
    imageUrl: 'https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg',
    dataAiHint: 'aloe vera'
  },
  {
    id: '89',
    nombre: 'Chontaduro',
    tipo: 'Otros peculiares o emergentes',
    nombreCientifico: 'Bactris gasipaes',
    familia: 'Arecaceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Palmera nativa cuyo fruto es muy nutritivo y popular en la región Pacífica. Requiere alta humedad y calor.',
    temporada: 'Enero - Abril',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Por semilla, la germinación es lenta.',
    tiempoCosecha: '3-5 años para empezar a producir.',
    plagasComunes: 'Picudo de la palma, Gualpa.',
    imageUrl: 'https://images.pexels.com/photos/14878486/pexels-photo-14878486.jpeg',
    dataAiHint: 'peach palm'
  },
  {
    id: '90',
    nombre: 'Feijoa',
    tipo: 'Otros peculiares o emergentes',
    nombreCientifico: 'Acca sellowiana',
    familia: 'Myrtaceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Arbusto que produce una fruta aromática de sabor agridulce, muy popular en el altiplano cundiboyacense.',
    temporada: 'Cosecha principal en primer semestre.',
    tipoDeSuelo: 'Franco, bien drenado.',
    tiempoSiembra: 'Por semilla o injerto.',
    tiempoCosecha: '3-4 años.',
    plagasComunes: 'Mosca de la fruta.',
    imageUrl: 'https://images.pexels.com/photos/5945763/pexels-photo-5945763.jpeg',
    dataAiHint: 'feijoa fruit'
  },
  {
    id: '91',
    nombre: 'Curuba',
    tipo: 'Otros peculiares o emergentes',
    nombreCientifico: 'Passiflora tarminiana',
    familia: 'Passifloraceae',
    region: 'Andina',
    clima: 'Frío',
    descripcionDetallada: 'Enredadera de la familia de las pasifloras, cuyo fruto alargado y ácido se usa para jugos. Típica de clima frío.',
    temporada: 'Todo el año.',
    tipoDeSuelo: 'Franco, rico en materia orgánica.',
    tiempoSiembra: 'Por semilla o esqueje.',
    tiempoCosecha: '1 - 1.5 años.',
    plagasComunes: 'Pulgones, mosca del botón floral.',
    imageUrl: 'https://images.pexels.com/photos/8975306/pexels-photo-8975306.jpeg',
    dataAiHint: 'banana passionfruit'
  },
  {
    id: '92',
    nombre: 'Níspero',
    tipo: 'Otros peculiares o emergentes',
    nombreCientifico: 'Manilkara zapota',
    familia: 'Sapotaceae',
    region: 'Caribe',
    clima: 'Cálido',
    descripcionDetallada: 'Árbol de crecimiento lento que produce un fruto dulce, de pulpa carnosa y color pardo. Muy resistente.',
    temporada: 'Variable.',
    tipoDeSuelo: 'Se adapta a muchos suelos, prefiere los bien drenados.',
    tiempoSiembra: 'Por semilla (lento) o injerto.',
    tiempoCosecha: '5-8 años (semilla).',
    plagasComunes: 'Mosca de la fruta.',
    imageUrl: 'https://images.pexels.com/photos/5945785/pexels-photo-5945785.jpeg',
    dataAiHint: 'sapodilla tree'
  },
  {
    id: '93',
    nombre: 'Fruto del Pan',
    tipo: 'Otros peculiares o emergentes',
    nombreCientifico: 'Artocarpus altilis',
    familia: 'Moraceae',
    region: 'Pacífica',
    clima: 'Húmedo',
    descripcionDetallada: 'Árbol de gran porte que produce un fruto grande y almidonado, que se consume cocido y es base alimenticia en zonas tropicales.',
    temporada: 'Variable.',
    tipoDeSuelo: 'Profundo, fértil y bien drenado.',
    tiempoSiembra: 'Por esquejes de raíz.',
    tiempoCosecha: '5-7 años.',
    plagasComunes: 'Antracnosis, cochinillas.',
    imageUrl: 'https://images.pexels.com/photos/6017600/pexels-photo-6017600.jpeg',
    dataAiHint: 'breadfruit tree'
  }
];

// In a real app, this function would fetch data from a Firestore collection.
export async function getCrops(): Promise<Crop[]> {
  // Simulate network delay to mimic a real API call
  await new Promise(resolve => setTimeout(resolve, 200));
  return crops;
}

// In a real app, this would fetch a specific crop by its ID from Firestore.
export async function getCropById(id: string): Promise<Crop | undefined> {
  await new Promise(resolve => setTimeout(resolve, 100));
  return crops.find(crop => crop.id === id);
}
